# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hyojeongson.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: sonhyojeong
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Front-end development" # used by search engines

  # Header and footer text
  header_text: >
     <p>I'm Hyojeong son, a Front-End Engineer at heybeauty.'손효정' 프론트엔드 개발자입니다. 헤이뷰티에서 일합니다.</p>
  header_text_feature_image:
  footer_text: >
   © hyojeong son. 2018

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "hyojeongson"
  google_plus:
  instagram: "sonhyojeong__"
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
